# fly.toml app configuration file generated for restorebyzzh on 2023-09-06T17:42:51+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restorebyzzh"
primary_region = "syd"

[build]
  image = "zzh118/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
